### ISSUE TITLE
Repeatable Quest giving Double Gil

### ISSUE THREAD

**Issue by ZurmaFFXI** [HomepointXI/Issues#553] opened 2021-08-29 22:11 UTC
**Date & Time**: 
8/29/2011 @ 6:05 pm EST

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Zurma

**Discord Name (if different from in game):**

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
45 Monk/ 22 Warrior

**NPC or Monster or item Name:**
IIIu Bohjaa

**Zone name:** 
Windurst Woods

**Coordinates (use `!where`):**
X:21 Y:-5 Z:125 (128)

**Item tool link (for items issues only):**
None

**Multi-boxing? (multiple clients on same connection):**
No

**Steps to reproduce:**
Talked to NPC
Selected Option to help NPC
Traded 3 Silk Thread
Received 1200 gil twice

**Any additional information:**
I verified in my gil count after each one that I did receive 2400 gil each trade in.
This happened each time I did this repeatable quest.  Did over roughly 10 trade ins since began my FFXI adventure and not once did it give me a single gil reward.

I did 3 other repeatable quests in other zones in Windurst and they all gave single gil rewards

**Name of Repeatable Quest that gave double gil:** 

Creepy Crawlies

**Names of other Repeatable Quests that gave single gil rewards:**

Teacher's Pet
The Postman Always K.O.'s Twice
Mandragora-Mad

![Zurma Crawler Double Gil Quest](https://user-images.githubusercontent.com/89349557/131266882-86f5ebc2-7ad6-4c0e-831a-72838ac983c9.png)

**Comment by EpicTaru** [comment] 2021-08-29 22:13
@ZurmaFFXI Please list the names of the other quests.  The double gil rewards is expected because of how the settings for the server are.

**Comment by ZurmaFFXI** [comment] 2021-08-29 22:16
Updated

**Comment by EpicTaru** [comment] 2021-08-29 22:20
Heep, if it is of any assistance, I noticed in the DSP code that the code for the Creepy Crawlies quest, out of all the quests listed, was the only one that used the global npc_util.lua to handle the processing of the completion of the quests/rewards for completion.

**Comment by Heepster03** [comment] 2021-08-30 01:10
![image](https://user-images.githubusercontent.com/8421725/131272180-34c22e9b-83d6-408b-b90b-8c757c8d8684.png)
The chat log is just telling you twice that you're getting it, but I'm only getting it once. But I will address the issue, nonetheless.

**Comment by Heepster03** [comment] 2021-08-30 14:07
Issue has been resolved and will be fixed in next update!

**Comment by ZurmaFFXI** [comment] 2021-08-30 14:57
Awesome, great job Heep and Epic :)

**Comment by Heepster03** [comment] 2021-08-30 15:06
Just to make it known, I already verified all of the quests mentioned and all are working as intended now for the update.

**Comment by EpicTaru** [comment] 2021-10-06 18:12
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.

**Closed as completed by EpicTaru** 2021-10-06 18:12 UTC
Labels: Fixed
