### ISSUE TITLE
Plenilune Embrace

### ISSUE THREAD

**Issue by fencedin** [HomepointXI/Issues#67] opened 2018-05-29 03:56 UTC
**Date & Time**: 
5/2818

**Client Version (use `/ver` in game):**

**Character Name:**

**Discord Name (if different from in game):**

**Nation:**

**Job(level)/Sub Job(level):**

**NPC or Monster or item Name:**
Gnole, Decrepit Gnole, Fusty Gnole

**Zone name:** 
Battilia Downs (S), Jugner Forest (S), Xacabard (S)

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
After fighting 100+ of these combined from the various maps, I have never seen them use Plenilune Embrace. Haven't seen it when they are on all fours or standing.

**Comment by EpicTaru** [comment] 2018-05-29 04:32
The Blue Tool lists them as mobs that use it. The Blue Tool is a direct pull from the db regarding TP moves and the mobs that show as said move being assigned to them.

You may need to wait for a long time for a mob to use a TP move.

I'll leave this ticket open for Heep or Immo or Autkast to provide further verification from custom files.

**Comment by Jessland86** [comment] 2018-05-29 04:35
The problem is the mob needs to be in a certain animation to do certain TP moves, This mob is one of them. I don't think these change 2>4 feet and vice versa.

**Comment by EpicTaru** [comment] 2018-05-29 04:36
Also, @fencedin, you need to complete all parts of the above form. Please do so asap.

**Comment by Jessland86** [comment] 2018-05-29 04:36
It's fine as they are not applicable

**Comment by nfaletra** [comment] 2018-05-29 15:56
There is definitely an issue with Gnoles using this ability. There are lots of Gnole issues in general. I'll clean them up and get it working for the next update.

**Comment by nfaletra** [comment] 2018-05-29 19:43
Fix't. Please look forward to it.

**Comment by nfaletra** [comment] 2018-06-11 05:57
Confirmed fixed.

**Closed by nfaletra** 2018-06-11 05:57 UTC
Labels: Upcoming maintenance
