### ISSUE TITLE
Failed to get the KI for dynamis

### ISSUE THREAD

**Issue by protocolz2025** [HomepointXI/Issues#557] opened 2021-09-10 00:57 UTC
**Date & Time**: 
2021/9/8

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
regzof

**Discord Name (if different from in game):**
fragile

**Nation:**
sandy

**Job(level)/Sub Job(level):**
blm99/rdm49

**NPC or Monster or item Name:**
Vial of shrouded sand

**Zone name:** 
sandy

**Coordinates (use `!where`):**
x:140 y:-2 z:120 (162)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
After defeating Shadow Lord, I reported back to Halver and clicked on the door to get the CS. Rank 6 obtained.
I then did the !tele vahzl command but the dynamis CS didn't happen.
Clicked on the Trail Markings in Southern Sandy didn't give me the "Vial of shrouded sand" KI neither.

**Any additional information:**

**Comment by EpicTaru** [comment] 2021-09-10 01:01
Duplicate of https://github.com/HomepointXI/Issues/issues/477

@Fragile2021, I'm already offline for the day, I will find you tomorrow to look into this issue further.

**Comment by EpicTaru** [comment] 2021-09-13 01:25
Value of character's **Dynamis_Status** variable was displaying as 1024 for some reason. Set the value of that variable to **0**. Had player then zone the character into Xarcabard after which the character received the cutscene there and the Dynamis_Status variable successfully updated correctly to 1. Character then examined the Trail Markings in South Sandy and successfully received the KI Shrouded Sand. Player is now able to enter Dynamis.

**Closed as completed by EpicTaru** 2021-09-13 01:25 UTC
Labels: Duplicate, Fixed
