### ISSUE TITLE
Doom not counting correctly

### ISSUE THREAD

**Issue by CaptSparklez** [HomepointXI/Issues#151] opened 2018-07-28 21:03 UTC
**Date & Time**: 28.07.2018, 22:15 GMT+2

**Client Version (use `/ver` in game):** 30180629_2

**Character Name:** Hakubai

**Discord Name (if different from in game):** Haku

**Nation:** San D'Oria

**Job(level)/Sub Job(level):** PLD99/WAR49

**NPC or Monster or item Name:** Bukhis

**Zone name:** Abyssea - Vunkerl

**Coordinates (use `!where`):** - 

**Item tool link (for items issues only):** -

**Multi-boxing? (multiple clients on same connection):** Yes

**Steps to reproduce:** Doom doesn't count properly, some numbers are skipped and replaced by dupes.

**Any additional information:** see screenshots

![hakubai_2018 07 28_221731](https://user-images.githubusercontent.com/18505482/43360679-76a8202a-92ba-11e8-9ece-e0ed9a8763b4.png)
![hakubai_2018 07 28_221740](https://user-images.githubusercontent.com/18505482/43360680-7b2557da-92ba-11e8-9b62-d81f490f7745.png)

**Comment by Heepster03** [comment] 2021-08-12 03:23
![image](https://user-images.githubusercontent.com/8421725/129133615-5ec8e565-3c7f-40fc-adf4-a04d76088529.png)

seems to be working as intended. closing!

**Closed by Heepster03** 2021-08-12 03:23 UTC
Labels: Investigation/Work in Progress, DSP issue
