### ISSUE TITLE
BCNM Getting sucked into the floor, mobs and players. 

### ISSUE THREAD

**Issue by Finalferrin** [HomepointXI/Issues#109] opened 2018-07-02 05:01 UTC
**Date & Time**: 
First time was June 29 around 10 PM I think
Second time was July 1, around 10 AM

**Client Version (use `/ver` in game):**

30180604_0

**Character Name:**
Terry

**Discord Name (if different from in game):**

NA

**Nation:**

Sandy

**Job(level)/Sub Job(level):**
Bst/Whm Level 40/20 First Time
War/Nin synced to 25/12 Second Time

**NPC or Monster or item Name:**
Sobbing Eyes First time
Dark Dragon Second Time

**Zone name:** 
Horlais Peak First Time
Balgas Dais Second Time

**Coordinates (use `!where`):**
Unknown, was able to finish the fight under the floor and exit in both instances

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

Yes

**Steps to reproduce:**
First Time: 2 Bst/Whm and a Thf/Dnc start the BCNM Under Observation. 2 BST, call pets and wait for timer. Then one BST attacks the hecteyes on the right. Links the other two and begins kiting by running back towards the entrance. When the group of mobs gets to the Stairs leading out of the center circle. They go under the floor with the pet. Except for the mob originally engaged, it stays above.  The others also come above when engaged and the name turns red.

Second Time: War/Nin and DNC/Nin duo rank 2-3 in Balgas Dais, fight begins normally, Dnc tanks Dark Dragon while War fights the eye. War attempted run out of range of a waterga, dark dragon used draw in attack and War went underneath the floor at the stairs leading out of the circle. 

**Any additional information:**
It only happens around the stair area. And in the case of Under Observation, it happened every time out of 5 fights.

**Comment by nfaletra** [comment] 2018-08-13 21:43
Caused by navmesh issues. Fixes in the next update.

**Comment by Jessland86** [comment] 2018-08-15 04:29
Fixed in today's maintenance.

**Closed by Jessland86** 2018-08-15 04:29 UTC
Labels: Fixed, Upcoming maintenance
