### ISSUE TITLE
Shantoto Blood_and_Glory no accepting Trade

### ISSUE THREAD

**Issue by nxnslite** [HomepointXI/Issues#608] opened 2022-06-04 19:03 UTC
**Date & Time**: 
06/04/2022

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
nxncure

**Discord Name (if different from in game):**
nxn_slite

**Nation:**
windy

**Job(level)/Sub Job(level):**
WHM 99

**NPC or Monster or item Name:**
None

**Zone name:** 
None

**Coordinates (use `!where`):**
None

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/17527/pole_of_trials

**Multi-boxing? (multiple clients on same connection):**
yes but dont care

**Steps to reproduce:**
get a pole do 300 PTS and trade

**Any additional information:**
Shantoto is not accepting the pole after the 300 PTS done and element removed.
cant get the [Map to the Annals of Truth]   (In real life... im not sure I would own a map of that name)
Thank you guys

**Comment by EpicTaru** [comment] 2022-06-04 21:58
@nxnslite does Shantotto say anything when you trade the Pole of Trials to her?

**Comment by EpicTaru** [comment] 2022-06-05 21:22
@nxnslite Please paste a screenshot here of your equipment screen that shows the latent effect of the Pole of Trials no longer reflecting in your stats

**Comment by nxnslite** [comment] 2022-06-05 21:24
![image](https://user-images.githubusercontent.com/30903928/172071192-ac057204-3057-4dfc-8dcb-47af0cdff058.png)

**Comment by nxnslite** [comment] 2022-06-05 21:24
> @nxnslite does Shantotto say anything when you trade the Pole of Trials to her?

nop

**Comment by nxnslite** [comment] 2022-06-05 23:54
quest completted 100% and how its all she tells me.
![image](https://user-images.githubusercontent.com/30903928/172075813-6bfee6ef-45fe-4852-88f1-f8781b5387ee.png)

**Comment by EpicTaru** [comment] 2022-06-06 01:07
~~@nxnslite Make sure to zone after completing the Curses, Foiled Again!? quest, then you should be prompted with the dialogue to start Curses, Foiled A-Golem.  Please complete that one too and then report here with what dialogue Shanny says.~~

**Comment by EpicTaru** [comment] 2022-06-06 15:10
@nxnslite cancel last comment, I'll fix your chara so you can go fight the WS NM in a few minutes.  I'll respond here once I'm done.

**Comment by EpicTaru** [comment] 2022-06-06 15:25
@nxnslite, the Pole of Trials has been deleted (**!delitem 17527**) from the chara and the KI **MAP_TO_THE_ANNALS_OF_TRUTH** has been added (**!addkeyitem MAP_TO_THE_ANNALS_OF_TRUTH**) to the chara.  Please now attempt to battle the WS NM.  If you encounter issues with spawning the WS NM, please respond here.  Otherwise, please also respond here if you were able to successfully spawn/defeat the WSNM and subsequently obtain the KI **ANNALS_OF_TRUTH** from the ??? after the WS NM is defeated.  You may also want to screenshot the death message of the WSNM should that be required here if issues are encountered with the obtaining of the KI **ANNALS_OF_TRUTH**.

**Comment by nxnslite** [comment] 2022-06-07 22:49
A portion of the lava here shines brighter than in the other areas. :(

**Comment by nxnslite** [comment] 2022-06-07 22:53
ps I dont know why but the quest is not in my quest log... that might be the problem now... 
and how the hell (cause i dont remember) I got the staff....  Surly I did trigger it.. long long time ago... in a Vanadiel far far away.

**Comment by EpicTaru** [comment] 2022-06-07 23:01
> A portion of the lava here shines brighter than in the other areas. :(

Is this the message you get when you get when you examine the ???

**Comment by nxnslite** [comment] 2022-06-07 23:13
yes

**Comment by EpicTaru** [comment] 2022-06-07 23:17
And you are at the ??? at the middle of the lava bridge?

**Comment by nxnslite** [comment] 2022-06-07 23:21
no the other 1... but the ??? at the bridge give nothing also... (bridge spawn another nm)

**Comment by EpicTaru** [comment] 2022-06-07 23:24
Ok, I'm having dinner, I'll look into the issue when I'm done.

**Comment by nxnslite** [comment] 2022-06-08 00:46
TY epic u saved a small familly member today.
its all fixed... As a sacrafice Ill do a retribution of that power to some monsters.

**Comment by EpicTaru** [comment] 2022-06-08 00:52
LOL, awesome, don't go crazy!

Glad the issue is resolved for you.  I'll research into the code surrounding the Staff WSNM quest later to see what may have happened to cause your issue to occur.  Closing ticket.

**Closed as completed by EpicTaru** 2022-06-08 00:52 UTC
Labels: Fixed
