### ISSUE TITLE
Unable to enter Dynamis unlimited times within the same real life day.

### ISSUE THREAD

**Issue by xendral** [HomepointXI/Issues#484] opened 2020-12-15 19:45 UTC
**Date & Time**: 12/15/2020 11:40 AM

**Client Version (use `/ver` in game):** 30191204_1

**Character Name:**Bozidar

**Discord Name (if different from in game):**CerisSquishy

**Nation:**Bastok

**Job(level)/Sub Job(level):**99Thf/49dnc

**NPC or Monster or item Name:**n/a

**Zone name:** n/a

**Coordinates (use `!where`):**Any Dynamis location

**Item tool link (for items issues only):**n/a

**Multi-boxing? (multiple clients on same connection):**no

**Steps to reproduce:**Attempting to enter dynamis more than once per real life 24 hours

**Any additional information:**
Blin, Bozidar, Squishy, Singsing, Louise, Bottoms, Harmony, Elmeow

**Comment by EpicTaru** [comment] 2020-12-15 19:58
Due to the fact that HomepointXI historically allowed unlimited dynamis entry, until it is determined (by the admins) that that "feature" is discontinued, players will be given the KI Rhapsody in Azure (Key Item ID 2886) until that determination is made.  One of the benefits that this Key Item allows is unlimited repeat entry into any dynamis zone without having to wait.

At that time, or when notice is given that the server configuration has been changed to once again allow unlimited entry into dynamis zones, the above Key Item will be removed from players accounts.

Key Item added to characters Harmony and Bozidar.  @xendral, please respond here when the other characters are logged in so they may also be given the key item.

**Comment by EpicTaru** [comment] 2020-12-15 21:41
Striking out the above, may not make a difference because of how the server is configured.

**Comment by EpicTaru** [comment] 2020-12-19 00:33
Need to do more testing, may have figured this out.  Will confirm after testing some more.

**Comment by EpicTaru** [comment] 2021-01-09 21:07
Confirmed that giving players the above mentioned KI will allow an unlimited number of entries into Dynamis zones a player already has gained access to.  Only requirement for the unlimited number of entries working with this KI is that the player must already have the KI prior to entering Dynamis.  If they do not, they are subject to the server midnight wait.

Key Item added to characters Blin, Squishy, Singsing, Louise, Bottoms, Harmony, and Elmeow.

Key Item added to characters Draxxus and Epictaru (multiple times to Epictaru as part of the testing).

Keeping this issue open as a method of tracking which players the KI was given to.

**Comment by EpicTaru** [comment] 2021-02-11 16:15
Key Item added to character Nevion.

Keeping this issue open as a method of tracking which players the KI was given to.

**Comment by EpicTaru** [comment] 2021-02-15 16:18
Key Item added to characters Eclipsed and Nyaan.

Keeping this issue open as a method of tracking which players the KI was given to.

**Comment by EpicTaru** [comment] 2021-02-28 16:18
Key item added to character Albian.

Keeping this issue open as a method of tracking which player(s) the KI was given to.

**Comment by EpicTaru** [comment] 2021-02-28 21:10
Key item added to character(s) Swarovski

Keeping this issue open as a method of tracking which player(s) the KI was given to.

**Comment by Draxxus82** [comment] 2021-03-01 15:26
need for Voltage and Proto

**Comment by EpicTaru** [comment] 2021-03-01 15:28
Key item added to character(s) Voltage and Proto.

Keeping this issue open as a method of tracking which player(s) the KI was given to.

**Comment by EpicTaru** [comment] 2021-03-21 23:06
Key item added to character(s) Warleaf.

Keeping this issue open as a method of tracking which player(s) the KI was given to.

**Comment by EpicTaru** [comment] 2021-03-25 22:25
Key item added to character(s) Gathin (also had to use !bring on him to pull him back into Dynamis because I forgot to add the KI BEFORE he entered). :/

Key item also added to character(s) Vixxen, Thotless, Lunaless, Lunarie, Clairdeluna, Orange, Juice.

Keeping this issue open as a method of tracking which player(s) the KI was given to.

**Comment by EpicTaru** [comment] 2021-03-29 13:43
Key item added to character(s) Gachauta.

Keeping this issue open as a method of tracking which player(s) the KI was given to.

**Comment by EpicTaru** [comment] 2021-04-08 19:11
Key item added to character(s) Meyrink, Minimey, Higuchi.

Keeping this issue open as a method of tracking which player(s) the KI was given to.

**Comment by EpicTaru** [comment] 2021-04-12 21:25
Key item added to character(s) Sporky.

Keeping this issue open as a method of tracking which player(s) the KI was given to.

**Comment by EpicTaru** [comment] 2021-04-21 16:21
Key item added to character(s) Vorpal.

Keeping this issue open as a method of tracking which player(s) the KI was given to.

**Comment by EpicTaru** [comment] 2021-04-25 14:40
Key item added to character(s) Kaizer.

Keeping this issue open as a method of tracking which player(s) the KI was given to.

**Comment by EpicTaru** [comment] 2021-04-28 20:53
Key Item removed from following characters:

04/28/21
Epictaru
Gathin
Nyaan
Albian
Lonelytortoise
Ogopogo
Popey
Onlan
Siryan
Swarovski
Petitepeste
Vixxen
Thotless
Lunaless
Lunarie
Clairdeluna
Orange
Juice
Majesticsun
Meyrink
Omobolasire
Kaizer

**Comment by EpicTaru** [comment] 2021-07-25 20:20
Fixed in maintenance prior to most recent.

**Closed by EpicTaru** 2021-07-25 20:20 UTC
Labels: Fixed, Upcoming maintenance
