### ISSUE TITLE
Excalibur weaponskill

### ISSUE THREAD

**Issue by Willthefluteboy** [HomepointXI/Issues#41] opened 2018-04-30 21:02 UTC
Date & Time: Monday, April 30, 2018

Client Version (use /ver in game): 30180203_1

Character Name: Reon

Discord Name (if different from in game): Will/Reon

Nation: Sandy

Job(level)/Sub Job(level): RDM 99 / DNC 49

NPC or Monster or item Name: X:-342 y:-5 Z:178 (131)

Zone name: Any zone with combat

Coordinates (use !where):  X:-342 y:-5 Z:178 (131)

Item tool link (for items issues only): 

Multi-boxing? (multiple clients on same connection): Tried with multi-boxing and without. Same result.

Steps to reproduce: Have Excalibur weapon at 85.

Any additional information: When Excalibur weapon was at 75 and I level synced between 75 and 99 I kept the weapon skill Knights of Round. When Excalibur weapon was upgraded to 85 and level synced between 75 and 85 the weaponskill was not available.

**Comment by nfaletra** [comment] 2018-05-04 22:28
Unsure of how this functions in retail. Need that info before moving forward with this. Or an admin makes an executive decision on it.

**Comment by nfaletra** [comment] 2018-05-14 15:50
After some more investigation into Equipment Scaling and this neat article: http://ffxiclopedia.wikia.com/wiki/Equipment_Scaling, this seems to be working as intended according to retail. Closing the ticket.

**Closed by nfaletra** 2018-05-14 15:50 UTC
Labels: DSP issue, Investigation/Work in Progress, On hold (For awhile), STICKY!
