### ISSUE TITLE
Rul'ude Gardens Crash.

### ISSUE THREAD

**Issue by lilaevyn** [HomepointXI/Issues#561] opened 2021-09-25 21:42 UTC
**Date & Time**: 
8/25/2021

**Client Version (use `/ver` in game):**
Version 30200904_2

**Character Name:**

Aevyn

**Discord Name (if different from in game):**

lilAevyn

**Nation:**
Windurst

**Job(level)/Sub Job(level):**
99 BLM/ 49 WHM

**NPC or Monster or item Name:**

N/A

**Zone name:** 
Ru'Lude Gardens

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

**Steps to reproduce:**

**Any additional information:**
I logged into Boyadha Tree, I teleported to Windurst and around the area itself. However, after attempted to go into Ru'lude Garden's my game would freeze, DC and crash. It knocked me off multiple times, especially even loading it would crash the client entirely. I was unable to even take 5 steps around the Garden's before a PC. It is currently only trying to zone into Garden's.

**Comment by EpicTaru** [comment] 2021-09-25 22:44
@lilaevyn describe please what you did in boyahda and in windurst prior to going to ru lude.

Also, please list what addons/plugins you have loaded, as well as if your client is running at an fps faster than 30 fps. 

Lastly, the fact that your client version is drastically different from the server version may also be a cause, if you are able at all to download the dat pack to align your client version with the server version, that may resolve the issue.

http://wiki.homepointxi.com/How_To:Version_Lock_Your_Client

**Comment by lilaevyn** [comment] 2021-09-26 00:11
In Boyadha I used a warp ring to return to Windurst where I changed jobs from Scholar to Blackmage. I put on my pre made set for Blackmage. Trashed some garbage items for space, then went to Lower Jeuno M ( pretty sure ) and then all the problems starteed. My client is running 50 FPS on the start up.

/load WindowerInput
/load Addons
/load Screenshot
/load Minimap
/load WatchEXP

and
/addon load distance
/addon load fps
/addon load timestamp
/addon load tparty
/addon load checker
/addon load ibar
/addon load macrofix

**Comment by EpicTaru** [comment] 2021-09-26 01:08
The game will run 30 fps if you don't change the fps manually. Are you using the fps addon to increase it? If so, please disable the fps addon. I highly doubt that the higher fps would be the cause though, it's more than likely the client mismatch occurring because of the version of your client.

**Comment by lilaevyn** [comment] 2021-09-26 16:12
Okay, I went back. I am running on 28-29 in the character selection screen. I'm gonna see about the mismatch of client.

**Comment by lilaevyn** [comment] 2021-09-26 16:17
Also, I am currently crashing as soon as I get into the game now. I can't play :/

**Comment by EpicTaru** [comment] 2021-09-26 16:37
Do the version lock then please report back if you still continue to have the instability after you are running on the server client version

**Comment by Heepster03** [comment] 2021-09-27 05:38
@lilaevyn let's us know what the status is. Is it working as intended when on the version locked version.

**Comment by lilaevyn** [comment] 2021-09-28 20:25
It worked just fine! Thank you for everything, and thanks to you guys and War we got it working!

**Comment by EpicTaru** [comment] 2021-09-28 20:26
Always glad to hear, @lilaevyn.  I'm going to go ahead and close this issue now.

**Closed as completed by EpicTaru** 2021-09-28 20:26 UTC
Labels: Version Mismatch, Could not reproduce, Fixed, Working As Intended
