### ISSUE TITLE
Unable to spawn VNM from Zilart Tier I

### ISSUE THREAD

**Issue by tuing** [HomepointXI/Issues#522] opened 2021-05-05 14:30 UTC
**Date & Time**: 
05/05/2021 21:20

Client Version (use /ver in game):
30191204_1

Character Name:
Meyrink
Tuing

Discord Name (if different from in game):
Meyrink

Nation:
Sandoria
Sandoria

Job(level)/Sub Job(level):
99 BLU/49 RDM
99 RDM/ 49 WHM

NPC or Monster or item Name:
n/a

Zone name:
n/a

Coordinates (use !where):
X: Y: Z:

Item tool link (for items issues only):
n/a

Multi-boxing? (multiple clients on same connection):
Yes

Steps to reproduce:
Trying to pop few VNM from Zilart Tier I namely Malleator Maurok, Sabotender Campeador, and Ildebrann with Meyrink and Tuing but the corresponding Rift not giving proper response where both char have the proper KI. Attached below the list of KI both char possess.

Meyrink's Abyssite KI:
![VW-KI](https://user-images.githubusercontent.com/26522986/117157794-14a0cd80-ade9-11eb-94e7-a19bfb41eff4.JPG)

Tuing's Abyssite KI:
![tuingVW](https://user-images.githubusercontent.com/26522986/117157830-1f5b6280-ade9-11eb-8fbc-c4340885fa53.JPG)

**Comment by EpicTaru** [comment] 2021-05-05 14:33
@Heepster03 @Jessland86 I've checked the KIs for Meyrink and Tuing, and even given myself any necessary KIs/quests needed in order for the Planar Rift NPCs to provide the correct response.  I can't get the correct response from any of the Planar Rift KIs so unless the HP code changed from the LD code for these rifts, I'm not sure why the rifts aren't providing the correct response.

**Comment by EpicTaru** [comment] 2021-05-05 14:50
Also attempted with character Spectre so has obtained all the KIs for the Ashen tier.  Also received the non-response from the Planar rift.

**Comment by neoffxi** [comment] 2021-05-06 00:40
The same issue for me. I couldn't initialize / pop the tier 1 NM. 
I was able to pop it before the update.

**Comment by EpicTaru** [comment] 2021-05-06 00:49
In the interests of not making players wait longer that necessary due to issues beyond their control, @neoffxi volunteered to use his voidstones for the purposes of popping Malleator Maurok for @tuing so that Tuing's charas could obtain the waist armor piece.

After verifying that character Neomorpheus had the **ASHEN_STRATUM_ABYSSITE** (**!haskeyitem 1447**) KI and that the quest VW_OP_101_DETOUR_TO_ZEPWELL was either accepted or completed (**!checkquest 5 102**),  voidstones were deleted from Neomorpheus's character (using **!delcurrency voidstones 1**) for each time the mob was force-spawned (using **!spawnmob 17629646**).

Leaving this issue open for any other players that may need any of the mobs in Zilart Tier I spawned (as long, of course, they also meet the requirements for normally being able to spawn the mobs themselves).

**Comment by Heepster03** [comment] 2021-05-06 02:59
Is it only those few?

**Comment by neoffxi** [comment] 2021-05-06 03:27
We were able to pop Ashen tier 2 and tier 3 with no issues. The issue seems to be with Ashen tier 1 only.

**Comment by EpicTaru** [comment] 2021-05-06 03:29
Chapter 4, tier 2 responded correctly a few days ago for @neoffxi. @tuing has been reclimbing thru chapters to re-obtain KIs for lower ones that he lost before the change was made so that KIs for lower tiers aren't lost when a chapter is cleared. I know he's been able to spawn all thru Jeuno tier 3 with no issues. He'll have to comment if he was able to do others between that and zilart tier 1.He was trying to get the waist item from Malleator Maurok when he ran into this issue. He was attempting to spawn using chara Meyrink. 

Earlier today, @neoffxi was able to get the correct response from the zilart tier 2 rift for Cath Palug and the correct response from the chapter 4, tier 1 rift for Isarukitsck. @tuing was able to get the correct response from the tier 3 rift for Aello.

Also recently, within this past week, @tuing was also able to get the correct response from the jeuno II, tier 1 and tier 3 rifts.

**Comment by neoffxi** [comment] 2021-05-06 03:34
Voidwatch NM tier 4 (Rw Nw Prt M Hrw) and tier 6 (Botulus Rex) are working as intended.

**Comment by Heepster03** [comment] 2021-05-06 16:44
Just merged and pulled the fixes for all tier 1 vwnms for the Ashen path. Fixes are live and are working on Homepoint. If you have an issue with a different mob not spawning, open another ticket. Enjoy!

**Closed** 2021-05-06 16:44 UTC
Labels: Fixed
