### ISSUE TITLE
No CS for Dynamis Entry in Xarcabard after achieving Rank 6

### ISSUE THREAD

**Issue by Draxxus82** [HomepointXI/Issues#477] opened 2020-11-23 20:21 UTC
**Date & Time**: 
11/22

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Draxxus

**Discord Name (if different from in game):**
Hauteclaire

**Nation:**
Windy

**Job(level)/Sub Job(level):**
99THF

**NPC or Monster or item Name:**

**Zone name:** 

**Coordinates (use `!where`):**

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Not at the time

**Steps to reproduce:**

**Any additional information:**
I believe it says leafs stacked in a certain way.

**Comment by EpicTaru** [comment] 2020-11-23 20:23
@Draxxus82 were you multiboxing when the issue first presented itself/when you received the cutscene in Xarc?

**Comment by EpicTaru** [comment] 2020-11-23 20:27
Also, please type /ver in game to find out your client version then either edit the ticket to supply the client version or supply it in a response here.

**Comment by Draxxus82** [comment] 2020-11-23 23:41
Ver 30191204_1 and yes when I first zoned in I was multiboxing

**Comment by Draxxus82** [comment] 2020-11-23 23:47
after cs in xara and cs at trail markings, the KI was obtained.

**Comment by EpicTaru** [comment] 2020-11-23 23:50
Value of character's **Dynamis_Status** variable was displaying as **256** for some reason.  Set the value of that variable to **0**.  Had player then zone the character into Xarcabard after which the character received the cutscene there and the **Dynamis_Status** variable successfully updated correctly to **1**.  Character then examined the Trail Markings in Windurst Walls and successfully received the KI Shrouded Sand. Player is now able to enter Dynamis.

Inconclusive at this point in time if this issue is due to multiboxing or not.  Issue was also experienced by a different player that wasn't multiboxing at the time (https://github.com/HomepointXI/Issues/issues/466).

**Comment by SilentPlunderer** [comment] 2021-03-29 13:34
Date & Time:
3/29/2021

Client Version (use /ver in game):
30191204_1

Character Name:
Gachauta

Discord Name (if different from in game):
GachaUta

Nation:
Bastok

Job(level)/Sub Job(level):
99 DRK/40 WAR

NPC or Monster or item Name:
(Key Item) Timeless Hourglass
Zone name:
Xarcabard
Coordinates (use !where):
X:101 Y:0 Z:-66 (66)
Item tool link (for items issues only):

Multi-boxing? (multiple clients on same connection):
No MultiBoxing

Steps to reproduce:
Completed Mission 5-2
Teleported to Xarcabard
Any additional information:
There is an unusual arrangement of pebbles here.

**Comment by EpicTaru** [comment] 2021-03-29 13:42
Value of character's **Dynamis_Status** variable was displaying as **128** for some reason.  Set the value of that variable to **0**.  Had player then zone the character into Xarcabard after which the character received the cutscene there and the **Dynamis_Status** variable successfully updated correctly to **1**.  Character then examined the Trail Markings in Windurst Walls and successfully received the KI Shrouded Sand. Character is now able to enter Dynamis.

Leaving this issue open for any other players that experience this issue.  Inconclusive at this point in time if this issue is due to multiboxing or not.  Issue was also experienced by different players in this ticket/other tickets at a different time that weren't multiboxing at the time.

**Comment by EpicTaru** [comment] 2021-05-17 18:37
https://github.com/HomepointXI/Issues/issues/527

**Comment by KaizerZitro** [comment] 2021-05-17 18:38
Date & Time:
13:30hrs (MX city) May/17/2021

Client Version (use /ver in game):
30191204_1

Character Name:
Yueri

Discord Name (if different from in game):
Zitro

Nation:
San d'oria

Job(level)/Sub Job(level):
THF99/DNC49

NPC or Monster or item Name:
Zone name:
Xarcabard

Coordinates (use !where):
X:596, Y:0, Z: -259

Item tool link (for items issues only):

Multi-boxing? (multiple clients on same connection):
Yes, main is Kaizer, Yueri and Manaward are alts

Steps to reproduce:
Just got Rank 6, talked to Halver and the King, then zoned into Xarcarbard for Dyna CS, didn't get the CS when zoning in

Any additional information:

**Comment by EpicTaru** [comment] 2021-05-17 18:45
@KaizerZitro The character's **Dynamis_Status** has the value indicating that they viewed the CS.  What happens when you examine the Trail Markings in any of the kingdoms?

**Comment by KaizerZitro** [comment] 2021-05-17 18:51
After examining the Trail markings in San d'Oria, got the proper CS and KI... It seems it just skipped the CS. Thanks!

**Comment by EpicTaru** [comment] 2021-05-17 18:52
Odd but good to hear, have fun in Neo Dynamis!!! You'll want to bring (a) friend(s)!!!

**Comment by Shoruto** [comment] 2021-07-09 23:51
Date & Time:
7/9/2021 @7:48 pm

Client Version (use /ver in game):
30191204_1

Character Name:
Sporuto

Discord Name (if different from in game):
Sporky

Nation:
Windurst rank 6

Job(level)/Sub Job(level):
99 PLD/49 WAR

NPC or Monster or item Name:
(Key Item) Timeless Hourglass

Zone name:
Xarcabard & Windurst Walls

Coordinates (use !where):
X:101 Y:0 Z:-66 (66)

Item tool link (for items issues only):

Multi-boxing? (multiple clients on same connection):
No

Steps to reproduce:
Completed Mission 5-2
Homepoint to Xarcabard and also tried zoning on foot

Any additional information:
Completed Rank 6 and was on a level 65+ job
No CS or KI from clicking on Windurst Walls Trail Markers.

**Comment by EpicTaru** [comment] 2021-07-10 00:29
@Shoruto Please let me know when you are next online so I can check your variables and assist in resolving this issue for you.

**Comment by Shoruto** [comment] 2021-07-10 09:50
Thanks, I'm going to log in and stay logged in.  If you need to talk to me in game and I don't respond feel free to ping me on discord.

**Comment by EpicTaru** [comment] 2021-07-10 20:10
Value of character's **Dynamis_Status** variable was displaying as **512** for some reason.  Set the value of that variable to **0**.  Had player then zone the character into Xarcabard after which the character received the cutscene there and the **Dynamis_Status** variable successfully updated correctly to **1**.  Character then examined the Trail Markings in Windurst Walls and successfully received the KI Shrouded Sand. Character is now able to enter Dynamis.

Leaving this issue open for any other players that experience this issue.  Inconclusive at this point in time if this issue is due to multiboxing or not.  Issue was also experienced by different players in this ticket/other tickets at a different time that also weren't multiboxing at the time.

**Comment by EpicTaru** [comment] 2021-09-02 23:20
Issue has been resolved for next update!!!

**Comment by EpicTaru** [comment] 2021-10-06 18:52
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.

**Closed by EpicTaru** 2021-10-06 18:52 UTC
Labels: Fixed
