### ISSUE TITLE
Scroll of Distract

### ISSUE THREAD

**Issue by skjdbobby** [HomepointXI/Issues#320] opened 2018-12-11 22:43 UTC
**Date & Time**: 12/11/18 5:30pm est
**Bug Date & Time**:12/11/18 4:45 - 5:00 am
**Bug Name**:Scroll of Distract
**Bug Page/Url**:n/a
**Bug Information**:game client crashes
**Steps To Reproduce The Bug**: use scroll of distract
**Additional Information**: none 

**Client Version (use `/ver` in game):** 
30181103_0

**Character Name:**
terraberth

**Discord Name (if different from in game):**
skjdbobby

**Nation:**
bastok

**Job(level)/Sub Job(level):**
rdm33/nin16

**NPC or Monster or item Name:**

**Zone name:** 
quifim island

**Coordinates (use `!where`):**
quifim island warp

**Item tool link (for items issues only):**
http://homepointxi.com/db/items/4912/scroll_of_distract

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**

opened scroll of distract

**Any additional information:**

**Comment by EpicTaru** [comment] 2018-12-11 22:48
Distract is a lvl35 RDM spell, you need to be that level on that job in order to open/learn that spell.

**Comment by skjdbobby** [comment] 2018-12-11 22:50
im sry man ill pay closer aention next time

**Comment by EpicTaru** [comment] 2018-12-11 22:50
it's no worries, happens to the best of us all, lol

**Comment by Jessland86** [comment] 2018-12-11 23:07
It still shouldn't crash the client when trying to use.

**Comment by nfaletra** [comment] 2018-12-31 15:45
Looks like it crashes clients if you already know the spell. Figuring out the cause.

**Comment by nfaletra** [comment] 2018-12-31 16:10
https://github.com/DarkstarProject/darkstar/pull/5525

**Comment by Jessland86** [comment] 2019-01-09 04:18
Fixed in today's maintenance.

**Closed by Jessland86** 2019-01-09 04:18 UTC
Labels: DSP issue, Fix submitted to DSP, Fixed, Upcoming maintenance
