### ISSUE TITLE
Light Skillchain Damage

### ISSUE THREAD

**Issue by Breogan7** [HomepointXI/Issues#409] opened 2019-11-23 23:58 UTC
**Date & Time**: 
11/23/2019 6:48 PM EST

**Client Version (use `/ver` in game):**
ver 30190904_1

**Character Name:**
Breogan

**Discord Name (if different from in game):**

**Nation:**
Bastok

**Job(level)/Sub Job(level):**
SAM99/DNC49

**NPC or Monster or item Name:**
Any

**Zone name:** 
Behemoth's Dominion

**Coordinates (use `!where`):**
E-8

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Breogan
Tripsmaximus

**Steps to reproduce:**
Creating Light Skillchains with Tachi: Fudo

**Any additional information:**
Any attempt to do a Light Skillchain using Tachi: Fudo, it results in 0 damage for the Skillchain. If I close the Skillchain w/ Tachi: Kaiten it does damage as normal. I've included 2 screenshots to show the closing of the Skillchain w/ both Kaiten and Fudo.

![2019-11-23_18-39-30](https://user-images.githubusercontent.com/17558522/69487151-325fba00-0e23-11ea-881b-c0f52aceb1d3.png)

![2019-11-23_18-41-24](https://user-images.githubusercontent.com/17558522/69487156-38ee3180-0e23-11ea-8b24-4fb58e2bdd53.png)

**Comment by Niobiritzu** [comment] 2019-12-07 01:27
Did you happen to do a self skillchain?
When I was using Bravura 119 (max), closing Light or Darkness results in a 0 dmg to the mob for the skillchain.

**Comment by simthra** [comment] 2020-03-22 18:18
I've just noticed today the same was happening to me while closing light (mandalic stab> victory smite) on my mnk and not having verethragna equipped.
Then I tried equipping the empy weapon and everything worked fine.
I can't say if this is working as intended or maybe the empy ws unlock is glitched.

**Comment by EpicTaru** [comment] 2021-07-25 21:02
Resolved in maintenance prior to most recent.

**Closed by EpicTaru** 2021-07-25 21:02 UTC
Labels: Fixed, Upcoming maintenance
