### ISSUE TITLE
SMN: Diabolos Quest

### ISSUE THREAD

**Issue by akahrimirai** [HomepointXI/Issues#244] opened 2018-10-07 20:18 UTC
**Date & Time**: 
10/07/18

**Client Version (use `/ver` in game):**
30180904_0

**Character Name:**
Mirai

**Discord Name (if different from in game):**
miraikari

**Nation:**
Sandoria

**Job(level)/Sub Job(level):**
SMN 1 / WHM 1

**NPC or Monster or item Name:**
n/a

**Zone name:** 
n/a

**Coordinates (use `!where`):**
n/a

**Item tool link (for items issues only):**
n/a

**Multi-boxing? (multiple clients on same connection):**
no

**Steps to reproduce:**
I'm trying to do the quest "Waking Dreams" for summoner pet Diabolos. I have talked to the quest starter, received the key item "Vial of Dream Incense" and made it to PSO'XJA > Shrouded Maw > Momento Circle and clicked the circle and it only gives me "Darkness Named" and "Test Your Mite" but no "Waking Dreams". I am on CoP - Dawn, way past the Darkness Named mission.

**Any additional information:**

**Comment by spectre99** [comment] 2018-10-07 21:05
I've done this quest in the past and have diabolos unlocked.  I just got the vial of dream incense KI and went to the fight area and I'm also only getting Darkness Named and Test Your MIght battles, so something definitely seems to be up.

**Comment by Heepster03** [comment] 2018-10-07 21:19
So... this is all kinds of f'd up. Test your Mite brings you to the Diabolos fight but you're synced to 40, also... you start on the bottom floor so all you see is Diremites. Diabolos is floating above you but at 40 yalms so you can't reach him. You'll just have to wait until this can be fixed.

**Comment by nfaletra** [comment] 2018-10-09 20:43
Fixed in next update

**Comment by Heepster03** [comment] 2018-10-10 05:34
Confirmed working.

**Closed by Heepster03** 2018-10-10 05:34 UTC
Labels: Fixed, Upcoming maintenance
