### ISSUE TITLE
Boulder Eater's in Gustav showing Too Weak and not Yielding EXP.

### ISSUE THREAD

**Issue by MVM1787** [HomepointXI/Issues#605] opened 2022-03-29 04:34 UTC
**Date & Time**: 
Monday March 28 2022  9:22 PM PST

 
**Client Version (use `/ver` in game)**: 30191204_1

**Character Name** : Ligerzero Pseyia, Dshiryu, Hyoga, Ikki, Shun

**Discord Name (if different from in game)**:Ligerzero

**Nation**: Sandy

**Job(level)/Sub Job(level)**: PUP 99/ DNC 49, the others are PUP 94 / MNK 47 Seyia is PUP 93 / MNK 46

**NPC or Monster or item Name**: Boulder Eaters

**Zone name**: Gustav Tunnels

**Coordinates (use `!where`)**:  X:-8 Y:-9 Z:144

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection)**: Yes

**Steps to reproduce**: Killing certain boulders eater's wont yield in exp gain and very little gil.

**Any additional information**: some of the boulder eater's in Gustav Tunnel's are showing as Too Weak to be worthwhile and are not giving out exp anymore when there that low. i have a Screenshot of the issue, they show Too Weak when synced down to level 93.

![Ligerzero_2022 03 28_211511](https://user-images.githubusercontent.com/12943935/160533803-bfc44584-317e-4143-98b5-3a7e66a2e61d.png)

![Ligerzero_2022 03 28_210514](https://user-images.githubusercontent.com/12943935/160533777-b1ada104-6746-4274-93e9-5d8ae27d9419.png)

**Comment by EpicTaru** [comment] 2022-03-29 04:48
Duplicate of

https://github.com/HomepointXI/Issues/issues/562
https://github.com/HomepointXI/Issues/issues/579

**Closed as completed by EpicTaru** 2022-03-29 04:48 UTC
Labels: Duplicate
