### ISSUE TITLE
Sent to different battlefield between the starter and other party members for ZM17 BC

### ISSUE THREAD

**Issue by tuing** [HomepointXI/Issues#510] opened 2021-04-19 09:56 UTC
Date & Time:
04/19/2021 @ 16:52 PM

Client Version (use /ver in game):
30191204_1

Character Name:
Minimey
Higuchi

Discord Name (if different from in game):
Meyrink

Nation:
Sandoria
Sandoria

Job(level)/Sub Job(level):
99 WHM/49 RDM
99 BRD/ 39 WHM

NPC or Monster or item Name:
Eald'narche

Zone name:
Celestial Nexus

Coordinates (use !where):
X:442 Y:-8 Z:-690 (0)

Item tool link (for items issues only):
n/a

Multi-boxing? (multiple clients on same connection):
Yes

Steps to reproduce:
Starting the BC fight for last fight of ZM and as usual the initiator (Higuchi) of the BC got cs and teleported to the battlefield with the boss spawned where the other members Minimey (who need the clearance as well) and Meyrink (helper) got teleported to different BC that are empty.

**Comment by EpicTaru** [comment] 2021-04-19 16:02
@tuing get all characters into the BCNM whenever you want to next attempt this and let me know, either on this ticket or in game, if the issue is still present.

**Comment by EpicTaru** [comment] 2021-04-19 16:19
Issue still existed when player tried entering battlefield again.  One character (the one that initiated the battle) is sent to the correct battlefield with the mob, any other character is sent to a different empty battlefield.

!brought Meyrink and Minimey to the battlefield that Higuchi was at so that the mob could be defeated.

**Comment by tuing** [comment] 2021-04-19 16:21
![Meyrink_2021 04 19_231951](https://user-images.githubusercontent.com/26522986/115269884-f2128180-a165-11eb-89ce-0b9e62627f19.png)

**Comment by EpicTaru** [comment] 2021-04-19 16:30
Since Higuchi was the character that initiated the battle, that character received the ending CS and his variables updated correctly, no adjustments needed for that character at all.

Force-completed Zilart mission **THE_CELESTIAL_NEXUS** (**!completemission 3 28**) and force-added Zilart mission **AWAKENING** (**!addmission 3 30**) for character Minimey.

Also verified that variable ZilartStatus reflected a value of **0** or set it to reflect such for character Minimey.

Character Meyrink was just along to assist with the battle so no adjustments were necessary for that character.

Congrats on completing the battle on all affected characters, @tuing!!!

Leaving this issue open for any other players that may also experience it.

**Comment by EpicTaru** [comment] 2021-08-10 18:36
fixed in upcoming update!

**Comment by EpicTaru** [comment] 2021-10-06 18:50
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.

**Closed by EpicTaru** 2021-10-06 18:50 UTC
Labels: Fixed
