### ISSUE TITLE
Divine Might

### ISSUE THREAD

**Issue by SychaeusAcerbas** [HomepointXI/Issues#416] opened 2020-02-11 00:19 UTC
**Date & Time**: 
Last night

**Client Version (use `/ver` in game):**
december update

**Character Name:**
Sychaeus, Sychcure, Elissa, Xenosis

**Discord Name (if different from in game):**
SychaeusAcerbas

**Nation:**
Sandy

**Job(level)/Sub Job(level):**
99thf/nin, 99rdm/whm, 99blm/rdm, idk

**NPC or Monster or item Name:**

the crystal warriors

**Zone name:** 

laloff amp.

**Coordinates (use `!where`):**

idk

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**

yes

**Steps to reproduce:**
Xenosis had a spare ark pentasphere, he couldnt get it to recognise at first, then went back and started DM (he had already done it on his main), we all went to home point 2 entrance, Xenosis was able to open the battlefield, and we entered. we got CS, completed battle, and exited (no CS), no credit. blank target in ru'avatau gives instructions on making an ark pentasphere.

**Any additional information:**

**Comment by EpicTaru** [comment] 2020-02-11 00:26
Are all of the affected characters on the same client version? Do they all belong to one player?

**Comment by SychaeusAcerbas** [comment] 2020-02-11 00:46
Sychcure is my cure please and was on my laptop, elissa was playing on her own laptop also same version (same connection but I play behind a VPN so not same IP) 

I'm not sure about xenosis's version. Diff player, different connection.

**Comment by EpicTaru** [comment] 2020-02-11 15:23
Did any of your characters go into the Shrine of Ru'Avitau for a cutscene and addition of the Divine Might quest in the Outlands section of your current quests **_prior_** to entry of the Divine Might fight?

This is **required**, as explained on FFXIclopedia (https://ffxiclopedia.fandom.com/wiki/Divine_Might)

![image](https://user-images.githubusercontent.com/26195580/74249936-86a26980-4caf-11ea-91c8-1c37b8726135.png)

**Comment by SychaeusAcerbas** [comment] 2020-02-11 15:40
Yes. We all got the CS and quest flagged before DM. We could have chosen the individual fights, and returning to the spot repeats the instruction on how to create the ark pentasphere.

**Comment by EpicTaru** [comment] 2020-02-11 15:52
Please let me know when you have all of the affected characters online so that I can check variables.

**Comment by EpicTaru** [comment] 2020-02-12 02:42
Checked relevant variables for player's characters.  All of the variable values seemed to not have updated like they would had the player successfully won the bcnm. 

Multiboxing issue is suspected to be the cause.

Informed player that he'd need to attempt the fight again on the characters to see if the variables update correctly this time around. I will observe the fight if I'm informed of when it'll occur. 

@SychaeusAcerbas please respond here when you are ready and going to attempt the bcnm again, please.

**Comment by SychaeusAcerbas** [comment] 2020-02-13 04:53
picked up 3 ark pentaspheres (even though it was thunder, and it shouldn't have let me). gonna try one now, if you're not up i'll have the other 2 for when you are.

**Comment by SychaeusAcerbas** [comment] 2020-02-13 05:24
my 2 and elissa all on some connection with our own ark pentasphere completed fine
(though on entrance it said - Another event was called while current event was running. The current battlefield clear time record for "" is 18 seconds. That record is held by nobody.

**Comment by EpicTaru** [comment] 2020-02-13 05:27
Sounds good! If you've successfully completed the quest, please close this ticket. I'll close it tomorrow if you haven't done so (or commented on here if you still have the issue).

**Closed** 2020-02-13 06:54 UTC
Labels: Investigation/Work in Progress, Multibox issue
