### ISSUE TITLE
Unable to proceed Sandy mission "Magicite"

### ISSUE THREAD

**Issue by Fragile2021** [HomepointXI/Issues#545] opened 2021-08-05 23:50 UTC
**Date & Time**: 
2021/8/6 

**Client Version (use `/ver` in game):**
30210706_0

**Character Name:**
Fragile and Higgs

**Discord Name (if different from in game):**
Fragile

**Nation:**
San d'Oria

**Job(level)/Sub Job(level):**
fragile BLM72/RDM36
higgs BLM75/RDM37

**NPC or Monster or item Name:**
Baudin 

**Zone name:** 
Upper Jeuno

**Coordinates (use `!where`):**
x:-72 y:0 z:80 (142)

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
Yes
I do know that doing the CS or quest at the same time is likely to cause problems.
So I talk to Baudin one at a time.

**Steps to reproduce:**
1. I talked to the Sandy embassy and seen the CS on the Door:San d'Orian Emb
2. Clicked on the Door: Audience Chamber
3. Forgot to talk to Aldo  (sigh)
4. Talked to Baudin in Upper Jeuno and he said something like "I cannot do anything at this point"
5. I realised that I didn't talk to Aldo, and I talked to Aldo and got the proper CS
6. Talked to Baudin again but he said "What I should do with my sister..." 

The "Crest of Davoi" quest is marked as completed and I didn't get the KI.
I even went to Davoi and I cannot walk thru the gate.

**Any additional information:**

**Comment by EpicTaru** [comment] 2021-08-05 23:59
@Fragile2021 I'll fix this for you in a few minutes, almost done eating

**Comment by EpicTaru** [comment] 2021-08-06 00:12
Duplicate of: https://github.com/HomepointXI/Issues/issues/471

Verified that above player(s) had completed the quest (**Crest of Davoi**) (**!checkquest 3 0**) and then gave the KI **Crest of Davoi** (**!addkeyitem 21**) to the player(s) so they are able to pass thru the Wall of Dark Arts if they wish to in the future.

**Comment by Fragile2021** [comment] 2021-08-06 00:19
I got the KI and proceeding the Davoi CS at the moment. Looks good to me. Thank you very much for your prompt support!

**Comment by Fragile2021** [comment] 2021-08-06 00:23
Another issue. I got black screen while watching the CS, and it stops in the middle. Pls help.

**Comment by EpicTaru** [comment] 2021-08-06 00:24
Which CS?  At the magicite?

**Comment by Fragile2021** [comment] 2021-08-06 00:24
Yes, the CS in Davoi.

**Comment by EpicTaru** [comment] 2021-08-06 00:25
Just noticed your client version number, this will very most definitely cause issues with many things in the game, CSes being one of them.

**Comment by Fragile2021** [comment] 2021-08-06 00:26
I see. Let me do the version lock thing and give it a try.

**Comment by EpicTaru** [comment] 2021-08-06 00:26
http://wiki.homepointxi.com/How_To:Version_Lock_Your_Client

**Comment by EpicTaru** [comment] 2021-08-10 16:59
Player was able to access the server with no further issues, closing this issue.

**Closed by EpicTaru** 2021-08-10 16:59 UTC
Labels: Duplicate, Fixed
