### ISSUE TITLE
Puppetmaster plug-ins not being accepted by Tateeya

### ISSUE THREAD

**Issue by LadyLux** [HomepointXI/Issues#142] opened 2018-07-16 00:23 UTC
**Date & Time**: 7/15/2018

**Client Version (use `/ver` in game):** 30180604_0

**Character Name:** Ladylux

**Discord Name (if different from in game):** Ladylux

**Nation:** Bastok

**Job(level)/Sub Job(level):** BLM99/RDM49

**NPC or Monster or item Name:** Tateeya 

**Zone name:**  Aht Urghan Whitegate

**Coordinates (use `!where`):** X:35 Y"-7 Z:43 (21)

**Item tool link (for items issues only):** Inhibitor II, Amplifier, Barrier Module, Dynamo II, Resister, Arcanic Cell, Regulator, Tension Spring IV, Heat Capacitor II, Loudspeaker IV, Tranquilizer III, Amplifier II, Accelerator IV, Scope III, Armor Plate IV, Shock Absorber III, Stabilizer IV, Dynamo III, Mana Jammer IV, Auto-Repair Kit IV, Mana Tank IV,  Speedloader II, Optic Fiber II, Damage Gauge II

**Multi-boxing? (multiple clients on same connection):** No

**Steps to reproduce:** Attempt to trade any of the above listed plug-ins to Tateeya with no resolve.

**Any additional information:**

**Comment by SqueeksAlaster** [comment] 2018-07-17 21:51
I am also having this issue
*Squeeks* 
item name : Resister

**Comment by simthra** [comment] 2019-04-19 19:08
A little update about attachments: most of them are now available and being accepted by Tateeya, with few exceptions:

* http://homepointxi.com/db/items/8462/speedloader; (sold by yoyoroon; tateeya won't accept it)
* http://homepointxi.com/db/items/2415/turbo_charger_ii;  (rararoon should sell it; missing item in recipe)
* http://homepointxi.com/db/items/9073/arcanic_cell_ii; (rararoon should sell it; should be craftable, missing whole recipe)
* http://homepointxi.com/db/items/2416/vivi-valve_ii; (rararoon should sell it; missing item in recipe)
* http://homepointxi.com/db/items/9233/mana_channeler_ii; (rararoon should sell it)

**Comment by Heepster03** [comment] 2021-08-12 04:22
I completely rebuilt the PUP Automaton shop in Nashmau and verified that Tateeya will accept the ones from the shop as intended.

**Comment by EpicTaru** [comment] 2021-10-06 20:53
![image](https://user-images.githubusercontent.com/26195580/136281430-2899a0c7-7d4e-45f5-9f5a-e7b46b98bdda.png)
This issue was resolved in yesterday's maintenance. Please open a new ticket should this issue re-occur.

**Closed as completed by EpicTaru** 2021-10-06 20:53 UTC
Labels: Fixed
