### ISSUE TITLE
CoP5-3 can't progress

### ISSUE THREAD

**Issue by Dankykong** [HomepointXI/Issues#507] opened 2021-04-17 15:39 UTC
**Date & Time**: 
April 17, 9:30AM

**Client Version (use `/ver` in game):**
30191204_1

**Character Name:**
Omobolasire, Majesticsun, Belledonna

**Discord Name (if different from in game):**
Sevvghetto

**Nation:**
Sandy, Bastok, Bastok

**Job(level)/Sub Job(level):**
99THF/49DNC, 99RDM/49BLM, 99WAR/49DNC

**NPC or Monster or item Name:**
Cid

**Zone name:** 
Metalworks

**Coordinates (use `!where`):**
x-12 y-10 z-1

**Item tool link (for items issues only):**

**Multi-boxing? (multiple clients on same connection):**
yes

**Steps to reproduce:**

**Any additional information:**
I finished all 3 paths for 5-3 but can't get the final mission CS from Cid and all mission logs are back on Ancient Flames Beckon

**Comment by EpicTaru** [comment] 2021-04-17 15:45
Duplicate of https://github.com/HomepointXI/Issues/issues/465

For the above character(s), to make sure they were showing the correct values indicating that they had completed all 3 paths, verification of the following variables was completed:

Variable COP_Tenzen_s_Path has a value of 11.

Variable COP_Ulmia_s_Path has a value of 8.

Variable COP_Louverance_s_Path has a value of 10.

After the above verifications, the value of the PromathiaStatus variable was verified to be set at 0 or updated to reflect that.

Promathia Mission FOR_WHOM_THE_VERSE_IS_SUNG was then added to their mission log (!addmission 6 60) as the current mission.

This doesn't appear to be a multiboxing issue, appears to be an issue in Cid's code. Issue started presenting itself after the server updated to the Dec. 2019 version.

**Closed by EpicTaru** 2021-04-17 15:45 UTC
Labels: Duplicate, Fixed
